[font]
size = 15.0

[font.normal]
family = "Cascadia Mono"
style = "ExtraLight"

[font.bold]
family = "Cascadia Mono"
style = "SemiLight"

[font.italic]
family = "Cascadia Mono"
style = "ExtraLight Italic"

