[colors.primary]
background = "0x1e1c31"
foreground = "0xcbe3e7"

[colors.cursor]
cursor = "0xa1efd3"
text = "0x1e1c31"

[colors.normal]
black = "0x1e1c31"
blue = "0x91ddff"
cyan = "0x87dfeb"
green = "0xa1efd3"
magenta = "0xd4bfff"
red = "0xf48fb1"
white = "0xcbe3e7"
yellow = "0xffe6b3"

[colors.bright]
black = "0x585273"
blue = "0x65b2ff"
cyan = "0x63f2f1"
green = "0x62d196"
magenta = "0xa37acc"
red = "0xf02e6e"
white = "0x8a889d"
yellow = "0xf2b482"
