[colors.primary]
background = "0x1b1e28"
foreground = "0xa6accd"

[colors.selection]
background = "0x303340"
text = "CellForeground"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "0x1b1e28"
blue = "0x89ddff"
cyan = "0xadd7ff"
green = "0x5de4c7"
magenta = "0xfcc5e9"
red = "0xd0679d"
white = "0xffffff"
yellow = "0xfffac2"

[colors.bright]
black = "0xa6accd"
blue = "0xadd7ff"
cyan = "0x89ddff"
green = "0x5de4c7"
magenta = "0xfae4fc"
red = "0xd0679d"
white = "0xffffff"
yellow = "0xfffac2"

