#!/usr/bin/env bash

# adapted from https://orrsella.com/2013/08/10/git-using-different-user-emails-for-different-repositories/

# CONFIG
name="Robin Thrift"
personal_email="thrift.d.robin@googlemail.com"

new_store_remote="newstore"
new_store_email="rthrift@newstore.com"

setIdentity() {
    local current_email local_email

    current_email="$(git config --get --local user.email)"

    local_email=("$@")

    if [[ "${current_email}" == "${local_email}" ]]; then
        printf "»  User: %s\n»  Mail: %s\n\n" "${name}" "${current_email}"
    else
        printf "»  User: %s\n»  Mail: %s\n\n" "${name}" "${local_email}"
        git config --local user.email "${local_email}"
    fi

    return 0
}


current_remote_url="$(git config --get --local remote.origin.url)"

# Disable case sensitivity for regex matching
shopt -s nocasematch

if [[ "$current_remote_url" =~ $new_store_remote ]]; then
    setIdentity "${new_store_email}"
    exit 0
else 
    setIdentity "${personal_email}"
    exit 0
fi

exit 0
