live_config_reload = true

import = ["~/.config/alacritty/colour.toml", "~/.config/alacritty/font.toml"]

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
persistent_logging = false
render_timer = false

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 0
multiplier = 0

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1.0
startup_mode = "Maximized"

[window.dimensions]
columns = 160
lines = 50

[window.padding]
x = 5
y = 2
