#!/usr/bin/env bash
case $(uname -s) in
    "Darwin")
    if [ "$1" == "charge" ]; then
        echo $(pmset -g batt | grep -o '[0-9]*%');
    fi;
    if [ "$1" == "source" ]; then
        echo $(pmset -g batt | grep -o '\(AC\|Battery\) Power' | grep -o 'AC\|Battery');
    fi;
esac;
